# libraries
library(casebase)
library(future.apply)
library(glmnet)
library(cbSCRIP)
library(parallel)
library(tictoc)
library(tidyverse)
library(foreach)
library(survival)
library(cmprsk)
library(glue)
library(here)
library(pec)
library(CoxBoost)
library(riskRegression)

#--------------- BRIER PLOTS FUNCTION -------------------

brier_fn <- function(n, p, num_true, setting,save_dir = here::here("paper","preds")){

data <- cbSCRIP:::gen_data(n = n, p = p, num_true = num_true,
                           setting = setting, iter = 123)

beta1 <- data$beta1
beta2 <- data$beta2
train <- data$train
test <- data$test
p <- sum(grepl("^X", names(train)))  # number of X-variables

# Test time-points for Brier score 
time_points <- sort(unique(test$ftime))

#restrict test time-points outside the training
tmax <- max(train$ftime[train$fstatus != 0], na.rm = TRUE)
time_points <- time_points[ is.finite(time_points) & time_points <= tmax ]
time_points <- na.omit(time_points[rep(c(T,F), length(time_points)/2)])

valid_event_times <- sort(unique(test$ftime[test$fstatus != 0]))
valid_event_times <- valid_event_times[valid_event_times <= tmax]

time_points <- seq(from = min(valid_event_times),
                   to = max(valid_event_times),
                   length.out = 50)

################## Brier score casebase #########################
set.seed(123)
fit_val_min <- cv_cbSCRIP(Surv(ftime, fstatus) ~ .,
                          train,
                          nlambda = 50,
                          alpha = 0.5,
                          ratio = 50)

res_cb_min <-varsel_perc(fit_val_min$fit.min$coefficients[1:p, 1], 
                              beta1)

print(plot(fit_val_min))

print(res_cb_min)

# Fit unpenalized model
fit_val_adj <- cbSCRIP(
    cb_data = fit_val_min$cb_data, # using case-base sample generated by cv function
    alpha = 0.5,
    lambda = fit_val_min$lambda.1se)


############################# CoxBoost ########################################
optim.res <- iCoxBoost(Hist(ftime, fstatus)~., data = train, cause = 1, cv = TRUE)

cbfit <-  iCoxBoost(Hist(ftime, fstatus)~., data = train, cause = 1,
                    stepno = optim.res$cv.res$optimal.step)

########################## iCR ###############################################
# Prepare data for coxph
iCS = two.i.CSlassos(data = train, nlambda = 100)



###################### Aalen-Johnson #########################################
fit.aj <- prodlim(Hist(ftime,fstatus)~1,data= train)

all_models <- list(
    "cbSCRIP" = fit_val_adj$refitted_models,
    "Aalen-Johansen" = fit.aj,
    "Boosted Fine-Gray" = cbfit,
    "iCR" = iCS
)

# Estimate Brier Scores
all_scores_event_1 <- Score(
    all_models,
    formula = Hist(ftime, fstatus) ~ 1,
    data = test,
    times = time_points,
    summary = "ibs",
    se.fit = FALSE,
    metrics = "Brier",
    cause = 1
)

data_brier <- all_scores_event_1$Brier$score %>%
    filter(model != "Null model") %>%
    mutate(model = as.character(model))

data_brier$title <- settings_tbl$desc[settings_tbl$setting == paste0("setting",setting)]

cbPalette <- c("#808080", "#D55E00", "#CC79A7", "#56B4E9", "#E69F00")

fname <- paste0("brier_setting", setting,
       "_N", n, "_p", p, "_k", num_true, ".png")

(plot2 <- ggplot(data = data_brier, aes(x = times, y = Brier, col = model)) +
  geom_line(size = 0.5) + 
  geom_line(data = filter(data_brier, model == "cbSCRIP"), linewidth  = 1) + 
  xlab("Follow-up time (years)") +
  ylab("Brier Score") +
  labs(color = "Models") +
  theme_bw() + scale_colour_brewer(palette = "Dark2") +
  labs(y = "Brier Score for Cause 1 Predictions") +
  scale_colour_manual(values=cbPalette) + 
  facet_grid(. ~ title))

print(plot2)

#------- save plot ------------------------------
ggsave(here("paper", "brier_figs", fname), plot2,
       width = 20, height = 12, units = "cm", dpi = 300)  # save file

#------- save data and objects ------------------
run_id <- sprintf("setting%d_N%d_p%d_k%d", setting, n, p, num_true)
dir.create(save_dir, recursive = TRUE, showWarnings = FALSE)
rds_path <- file.path(save_dir, paste0("results_", run_id, ".rds"))

results <- list(
    meta = list(N = n, p = p, k = num_true, setting = setting,
                time_points = time_points, seed = 123,
                fname = fname),
    data = list(train = train, test = test, beta1 = beta1, beta2 = beta2),
    models = list(
        fit_val_min = fit_val_min,
        fit_val_adj = fit_val_adj,
        cbfit = cbfit,
        iCS = iCS,
        fit_aj = fit.aj
    ),
    scores = all_scores_event_1,
    brier_table = data_brier,
    plot = plot2
)

saveRDS(results, rds_path, compress = "xz")
message("Saved run to: ", rds_path)

invisible(results) 
}


#------------ CIF PLOT FUNCTION ----------------------
cif_plot_fn <- function(n, p, num_true,setting){
    
# load a saved run and tweak the plot label without recomputing
run_id <- sprintf("setting%d_N%d_p%d_k%d", setting, n, p, num_true)
res <- readRDS(here::here("paper","preds", paste0("results_", run_id, ".rds")))
cif_title <- settings_tbl$desc[settings_tbl$setting == paste0("setting",setting)]   
    
#data from saved object
time_points <- res$meta$time_points
test <- res$data$test  
train <- res$data$train
    
#-------------- De-biased CASEBASE -------------
    # (unpenalized based on selection)
    # Estimate absolute risk curve 
    risk_cb <- absoluteRisk(
        object = res$models$model_cb, 
        newdata = test,
        time = time_points,
        method = "numerical"
    )
    
    risk_cb <- risk_cb[-1, ]
    risk_cb <- as.numeric(unlist(rowMeans(risk_cb), use.names = FALSE))
    
#------------------- CASEBASE ------------------
    # (penalized based on selection)
    
    # Estimate absolute risk curve 
    # risk_pencb <- predictRisk(
    #     res$models$fit_val_min$fit.min,
    #     newdata = test,
    #     time = time_points, 
    #     cause = 1)
    # 
    # risk_pencb <- as.numeric(colMeans(risk_pencb))
    
#-------------- Fine-Grey -----------
    # Estimate absolute risk curve 
    
    risk_fg <- predictRisk(res$models$cbfit, 
                           newdata = test, 
                           times = time_points, 
                           cause = 1)
    
    risk_fg <- as.numeric(colMeans(risk_fg))
    
#-------------- Cox EN (?) -----------
    # Estimate absolute risk curve
    
    risk_iCS <- predictRisk(res$models$iCS, 
                            newdata = test, 
                            times = time_points, 
                            cause = 1)
    risk_iCS <- as.numeric(colMeans(risk_iCS))
    
#--------- combine all -------------------
risk_all <-dplyr::bind_rows(
        data.frame(
            Time = time_points,
            Method = "cbSCRIP",
            Type = "CB",
            Risk = risk_cb,
            stringsAsFactors = FALSE),
        # data.frame(
        #     Time = time_points,
        #     Method = "Case-base",
        #     Type = "CB",
        #     Risk = risk_pencb,
        #     stringsAsFactors = FALSE),
        data.frame(
            Time = time_points,
            Method = "Boosted Fine-Gray",
            Type = "other",
            Risk = risk_fg,
            stringsAsFactors = FALSE),
        data.frame(
            Time = time_points,
            Method = "iCR",
            Type = "other",
            Risk = risk_iCS,
            stringsAsFactors = FALSE) 
    ) %>%
        dplyr::filter(Time <= 60)
    
#--------- PLOT ------
risk_all$title <- settings_tbl$desc[settings_tbl$setting == paste0("setting",setting)]
    
cbPalette <- c("#CC79A7", "#E69F00","#D55E00", "#56B4E9")

(risk_plot <- ggplot(risk_all, aes(x = Time, y = Risk, colour = Method)) +
        # geom_line for smooth curve
        geom_line(data = dplyr::filter(risk_all, Type == "CB"), linewidth = 1) +
        geom_step(data = dplyr::filter(risk_all, Type != "CB"), linewidth = 1) +
        ylim(c(0, 1)) + theme(text = element_text(size = 30)) + 
        xlab("Time (in Years)") +
        ylab("Absolute Risk") + 
        theme_bw()+ scale_colour_brewer(palette = "Dark2")+
        scale_colour_manual(values=cbPalette) + 
        facet_grid(. ~ title))
            


#------- save plot ------------------------------
img_dir <- here::here("paper","cif_figs")
file_name <- file.path(img_dir, paste0("cif_", run_id,".png"))
    
ggsave(file_name, risk_plot,
           width = 20, height = 12, units = "cm", dpi = 300) 
}



#------------ CIF DATA FUNCTION ----------------------
cif_data_fn <- function(n, p, num_true,setting){
    
    # load a saved run and tweak the plot label without recomputing
    run_id <- sprintf("setting%d_N%d_p%d_k%d", setting, n, p, num_true)
    res <- readRDS(here::here("paper","preds", paste0("results_", run_id, ".rds")))
    cif_title <- settings_tbl$desc[settings_tbl$setting == paste0("setting",setting)]   
    
    #data from saved object
    time_points <- res$meta$time_points
    test <- res$data$test  
    train <- res$data$train
    
    #-------------- De-biased CASEBASE -------------
    # (unpenalized based on selection)
    # Estimate absolute risk curve 
    risk_cb <- absoluteRisk(
        object = res$models$fit_val_adj$refitted_models, 
        newdata = test,
        time = time_points,
        method = "numerical"
    )
    
    risk_cb <- risk_cb[-1, ]
    risk_cb <- as.numeric(unlist(rowMeans(risk_cb), use.names = FALSE))
    
    #------------------- CASEBASE ------------------
    # (penalized based on selection)
    
    # Estimate absolute risk curve 
    # risk_pencb <- predictRisk(
    #     res$models$fit_val_min$fit.min,
    #     newdata = test,
    #     time = time_points, 
    #     cause = 1)
    # 
    # risk_pencb <- as.numeric(colMeans(risk_pencb))
    
    #-------------- Fine-Grey -----------
    # Estimate absolute risk curve 
    
    risk_fg <- predictRisk(res$models$cbfit, 
                           newdata = test, 
                           times = time_points, 
                           cause = 1)
    
    risk_fg <- as.numeric(colMeans(risk_fg))
    
    #-------------- Cox EN (?) -----------
    # Estimate absolute risk curve
    
    risk_iCS <- predictRisk(res$models$iCS, 
                            newdata = test, 
                            times = time_points, 
                            cause = 1)
    risk_iCS <- as.numeric(colMeans(risk_iCS))
    
    #--------- combine all -------------------
    risk_all <-dplyr::bind_rows(
        data.frame(
            Time = time_points,
            Method = "cbSCRIP",
            Type = "CB",
            Risk = risk_cb,
            stringsAsFactors = FALSE),
        # data.frame(
        #     Time = time_points,
        #     Method = "Case-base",
        #     Type = "CB",
        #     Risk = risk_pencb,
        #     stringsAsFactors = FALSE),
        data.frame(
            Time = time_points,
            Method = "Boosted Fine-Gray",
            Type = "other",
            Risk = risk_fg,
            stringsAsFactors = FALSE),
        data.frame(
            Time = time_points,
            Method = "iCR",
            Type = "other",
            Risk = risk_iCS,
            stringsAsFactors = FALSE) 
    ) %>%
        dplyr::filter(Time <= 60)
    
    return(risk_all) 
}

#---------------- PLOT GRID ----------------------

plot_grid <- function(input_name,out_name){

dir.create(dirname(out_name), recursive = TRUE, showWarnings = FALSE)

# --- SAVE TO FILE ---
grDevices::png(out_name, width = 2400, height = 1600, res = 200)
grid::grid.newpage()
vp <- grid::viewport(layout = grid::grid.layout(2, 3))
grid::pushViewport(vp)

for (i in seq_along(input_name)) {
    r <- ((i - 1) %/% 3) + 1
    c <- ((i - 1) %%  3) + 1
    img <- png::readPNG(input_name[i])               
    grid::grid.raster(img, vp = grid::viewport(layout.pos.row = r, layout.pos.col = c))
}
}
